### ISSUE TITLE
Melhorar a Documentação: Instalar e Configurar Kubernetes

### ISSUE THREAD

**Issue by kauaneiras** [FGA-GCES/ESO-Documentacao#7]
#### **1. Estrutura Inicial**
- [ ] Adicionar título claro, como: **"Guia de Instalação e Configuração do Kubernetes"**.
- [ ] Criar uma introdução breve explicando o objetivo da instalação e o contexto do uso do Kubernetes.

---

#### **2. Pré-requisitos**
- [ ] Listar os pré-requisitos básicos:
  - Sistema operacional suportado (Linux, macOS).
  - Docker instalado e funcionando.
  - Conexão com a internet.
---
##### **Instalar Docker**
- [ ] Explicar brevemente o que é Docker e o motivo de utilizá-lo.
- [ ] Adicionar comandos para instalação
- [ ] Adicionar comando para testar a instalação

##### **Instalar Kind (Kubernetes In Docker)**
- [ ] Explicar o que é Kind e por que usá-lo.
- [ ] Adicionar instruções para instalação em Linux
- [ ] Adicionar comando para testar a instalação
- [ ] Adicionar instruções para instalação em macOS com Homebrew
- [ ] Incluir link para mais opções de instalação

##### **Instalar kubectl**
- [ ] Explicar brevemente o que é o kubectl e sua importância.
- [ ] Adicionar instruções para instalação em Linux
- [ ] Adicionar comando para testar a instalação
- [ ] Adicionar instruções para instalação em macOS com Homebrew
- [ ] Incluir link para mais opções de instalação

##### **Instalar Helm**
- [ ] Explicar brevemente o que é Helm e seu uso no Kubernetes.
- [ ] Adicionar instruções para instalação
- [ ] Adicionar comando para testar a instalação
- [ ] Incluir link para mais opções de instalação

##### **Criar Cluster Kubernetes com Kind**
- [ ] Explicar o propósito do Kind na criação de clusters locais para desenvolvimento.
- [ ] Adicionar comando para criar o cluster
- [ ] Adicionar comando para salvar o arquivo kubeconfig
- [ ] Explicar como testar a configuração com o kubectl

---

#### **5. Testar Instalações**
- [ ] Adicionar uma seção dedicada para verificar se todas as ferramentas estão funcionando:
  - `docker version`
  - `kind --version`
  - `kubectl version --client`
  - `helm version`

---

#### **6. Melhorias Gerais**
- [ ] Remover o passo de clonar repositórios desnecessários, como `kubernetes-para-devs`.
- [ ] Garantir links para a documentação oficial de cada ferramenta para referência adicional:
  - [Kind](https://kind.sigs.k8s.io/)
  - [kubectl](https://kubernetes.io/docs/tasks/tools/#kubectl)
  - [Helm](https://helm.sh/docs/intro/install/)

**Comment by CarolCoCe** [comment]
Essa parte já foi feita
